[versions]
ktor = "3.3.2"
kotlin = "2.2.21"

[libraries]
telegram = { group = "dev.inmo", name = "tgbotapi", version = "29.0.0" }
envconf = { group = "dev.schlaubi", name = "stdx-envconf", version = "2.0.0" }
mongodb-driver-kotlin-coroutine = { group = "org.mongodb", name = "mongodb-driver-kotlin-coroutine", version = "5.6.1" }

kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version = "1.9.0" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version = "0.7.1" }

ktor-server-netty = { group = "io.ktor", name = "ktor-server-netty", version.ref = "ktor" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }

logback-classic = { group = "ch.qos.logback", name = "logback-classic", version = "1.5.21" }
kotlin-logging = { group = "io.github.oshai", name = "kotlin-logging", version = "7.0.13" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
